jobs:
  build:
    working_directory: ~/CircleCIApplitoolsCypress
    docker:
    - image: cypress/base:10
    steps:
    - checkout
    - restore_cache:
        keys:
        - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
        - v2-deps-{{ .Branch }}-
        - v2-deps-
    - run: npm ci
    - save_cache:
        key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
        paths:
        - ~/.npm
        - ~/.cache
    - run: {}
      command: |
        export APPLITOOLS_BATCH_ID=`echo $CIRCLE_SHA1`
        echo $APPLITOOLS_BATCH_ID
        npm run cy:run -- --spec "cypress/integration/examples/actions.spec.js"
workflows:
  version: 2
  workflow:
    jobs:
    - build
